name: Exoserver — build & deploy on VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Sincroniza el repo al home del usuario no-root
      - name: Sync sources to VPS
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -az --delete
          path: .
          remote_path: /home/${{ secrets.VPS_USER }}/exoserver-src
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}

      # Build con nerdctl (requiere sudo pero SOLO para nerdctl) + deploy con kubeconfig limitado
      - name: Build image and rollout in K3s
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail
            cd ~/exoserver-src

            # build de imagen local para containerd de k3s
            TAG=${GITHUB_SHA}
            sudo nerdctl -n k8s.io build -t exoserver:${TAG} -t exoserver:latest .

            # aplicar manifests y actualizar Deployment usando kubeconfig limitado
            KUBECONFIG=/home/${USER}/.kube/config-exohunter kubectl apply -f k8s/

            KUBECONFIG=/home/${USER}/.kube/config-exohunter kubectl -n exohunter set image \
              deploy/exoserver-deployment exoserver=exoserver:${TAG}

            KUBECONFIG=/home/${USER}/.kube/config-exohunter kubectl -n exohunter rollout status \
              deploy/exoserver-deployment --timeout=300s

            KUBECONFIG=/home/${USER}/.kube/config-exohunter kubectl -n exohunter get pods -o wide
